<template>
  <div class="exam-container">
    <!-- 背景装饰 -->
    <div class="bg-decoration">
      <div class="bg-circle bg-circle-1"></div>
      <div class="bg-circle bg-circle-2"></div>
    </div>

    <!-- 页头 -->
    <div class="page-header">
      <div class="header-title">
        <svg class="header-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
          <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20"/>
          <path d="M8 7h6"/>
          <path d="M8 11h8"/>
        </svg>
        <h1>智能组卷</h1>
      </div>
      <div class="header-actions">
        <el-button @click="showQuestionDialog = true" class="btn-secondary">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
            <path d="M12 5v14M5 12h14"/>
          </svg>
          题目管理
        </el-button>
        <el-button type="primary" class="btn-primary" @click="showAutoGenerateDialog = true">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
            <path d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09Z"/>
          </svg>
          智能组卷
        </el-button>
      </div>
    </div>

    <!-- 标签页 -->
    <el-tabs v-model="activeTab" class="glass-tabs" @tab-change="handleTabChange">
      <el-tab-pane label="试卷列表" name="papers">
        <!-- 筛选表单 -->
        <div class="glass-card filter-card">
          <el-form :inline="true" class="query-form">
            <el-form-item label="试卷名称">
              <el-input v-model="paperQuery.keyword" placeholder="请输入试卷名称" clearable style="width: 200px" />
            </el-form-item>
            <el-form-item label="状态">
              <el-select v-model="paperQuery.status" placeholder="请选择状态" clearable style="width: 140px">
                <el-option label="草稿" value="draft" />
                <el-option label="已发布" value="published" />
                <el-option label="已归档" value="archived" />
              </el-select>
            </el-form-item>
            <el-form-item label="组卷方式">
              <el-select v-model="paperQuery.sourceType" placeholder="请选择" clearable style="width: 140px">
                <el-option label="手动组卷" value="manual" />
                <el-option label="智能组卷" value="auto" />
                <el-option label="模板组卷" value="template" />
              </el-select>
            </el-form-item>
            <el-form-item>
              <el-button type="primary" @click="loadPapers">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" width="16" height="16">
                  <circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/>
                </svg>
                搜索
              </el-button>
              <el-button @click="resetPaperQuery">重置</el-button>
            </el-form-item>
          </el-form>
        </div>

        <!-- 试卷列表 -->
        <div class="glass-card paper-list-card">
          <div v-loading="paperLoading">
            <div v-if="papers.length === 0" class="empty-state">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" width="80" height="80">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                <polyline points="14 2 14 8 20 8"/>
              </svg>
              <p>暂无试卷</p>
              <el-button type="primary" @click="showAutoGenerateDialog = true">立即组卷</el-button>
            </div>
            <div v-else class="paper-grid">
              <div v-for="p in papers" :key="p.id" class="paper-card">
                <div class="paper-card-header">
                  <div class="paper-title-row">
                    <span class="paper-title">{{ p.title }}</span>
                    <el-tag :type="getStatusType(p.status)" size="small">{{ getStatusText(p.status) }}</el-tag>
                  </div>
                  <div class="paper-type-tag">
                    <el-tag size="small" effect="plain">{{ getSourceTypeText(p.sourceType) }}</el-tag>
                  </div>
                </div>
                <div class="paper-card-body">
                  <div class="stat-item">
                    <span class="stat-label">总分</span>
                    <span class="stat-value">{{ p.totalScore }}分</span>
                  </div>
                  <div class="stat-item">
                    <span class="stat-label">题目</span>
                    <span class="stat-value">{{ p.questionCount }}题</span>
                  </div>
                  <div class="stat-item">
                    <span class="stat-label">时限</span>
                    <span class="stat-value">{{ p.timeLimit }}分钟</span>
                  </div>
                  <div class="stat-item">
                    <span class="stat-label">及格</span>
                    <span class="stat-value">{{ p.passScore }}分</span>
                  </div>
                </div>
                <div class="paper-card-footer">
                  <span class="paper-date">创建于 {{ formatDate(p.createTime) }}</span>
                  <div class="paper-actions">
                    <el-button type="primary" link size="small" @click="handlePreview(p)">预览</el-button>
                    <el-dropdown trigger="click" @command="(cmd) => handleCommand(cmd, p)">
                      <el-button type="info" link size="small">
                        更多
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="12" height="12">
                          <path d="m6 9 6 6 6-6"/>
                        </svg>
                      </el-button>
                      <template #dropdown>
                        <el-dropdown-menu>
                          <el-dropdown-item command="publish" :disabled="p.status === 'published'">发布</el-dropdown-item>
                          <el-dropdown-item command="dispatch">下发考试</el-dropdown-item>
                          <el-dropdown-item command="statistics">查看统计</el-dropdown-item>
                          <el-dropdown-item command="delete" divided>删除</el-dropdown-item>
                        </el-dropdown-menu>
                      </template>
                    </el-dropdown>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <el-pagination
            v-if="papers.length > 0"
            v-model:current-page="paperQuery.page"
            v-model:page-size="paperQuery.pageSize"
            :total="paperTotal"
            :page-sizes="[8, 16, 24, 32]"
            layout="total, sizes, prev, pager, next, jumper"
            class="pagination"
            @size-change="loadPapers"
            @current-change="loadPapers"
          />
        </div>
      </el-tab-pane>

      <el-tab-pane label="考试记录" name="records">
        <div class="glass-card filter-card">
          <el-form :inline="true" class="query-form">
            <el-form-item label="试卷">
              <el-select v-model="recordQuery.paperId" placeholder="请选择试卷" clearable style="width: 200px">
                <el-option v-for="p in papers" :key="p.id" :label="p.title" :value="p.id" />
              </el-select>
            </el-form-item>
            <el-form-item label="状态">
              <el-select v-model="recordQuery.status" placeholder="请选择状态" clearable style="width: 140px">
                <el-option label="未开始" value="not_started" />
                <el-option label="进行中" value="in_progress" />
                <el-option label="已提交" value="submitted" />
                <el-option label="已评分" value="graded" />
              </el-select>
            </el-form-item>
            <el-form-item>
              <el-button type="primary" @click="loadRecords">搜索</el-button>
              <el-button @click="resetRecordQuery">重置</el-button>
            </el-form-item>
          </el-form>
        </div>

        <div class="glass-card">
          <el-table :data="records" v-loading="recordLoading" stripe>
            <el-table-column prop="userName" label="考生" width="120" />
            <el-table-column prop="paperTitle" label="试卷" min-width="180" />
            <el-table-column prop="status" label="状态" width="100">
              <template #default="{ row }">
                <el-tag :type="getRecordStatusType(row.status)" size="small">
                  {{ getRecordStatusText(row.status) }}
                </el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="score" label="得分" width="80">
              <template #default="{ row }">
                {{ row.score ?? '-' }}
              </template>
            </el-table-column>
            <el-table-column prop="correctRate" label="正确率" width="100">
              <template #default="{ row }">
                {{ row.correctRate ? row.correctRate + '%' : '-' }}
              </template>
            </el-table-column>
            <el-table-column prop="isPassed" label="结果" width="80">
              <template #default="{ row }">
                <el-tag v-if="row.isPassed !== null" :type="row.isPassed ? 'success' : 'danger'" size="small">
                  {{ row.isPassed ? '及格' : '不及格' }}
                </el-tag>
                <span v-else>-</span>
              </template>
            </el-table-column>
            <el-table-column prop="duration" label="用时" width="100">
              <template #default="{ row }">
                {{ row.duration ? formatDuration(row.duration) : '-' }}
              </template>
            </el-table-column>
            <el-table-column prop="createTime" label="考试时间" width="160">
              <template #default="{ row }">
                {{ formatDate(row.createTime) }}
              </template>
            </el-table-column>
            <el-table-column label="操作" width="100" fixed="right">
              <template #default="{ row }">
                <el-button type="primary" link size="small" @click="viewAnswerDetails(row)">查看详情</el-button>
              </template>
            </el-table-column>
          </el-table>
          <el-pagination
            v-model:current-page="recordQuery.page"
            v-model:page-size="recordQuery.pageSize"
            :total="recordTotal"
            :page-sizes="[10, 20, 50, 100]"
            layout="total, sizes, prev, pager, next"
            class="pagination"
            @size-change="loadRecords"
            @current-change="loadRecords"
          />
        </div>
      </el-tab-pane>

      <el-tab-pane label="统计分析" name="statistics">
        <div class="glass-card">
          <el-row :gutter="24" class="stats-row">
            <el-col :span="6">
              <div class="stat-card">
                <div class="stat-icon-wrapper blue">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                    <polyline points="14 2 14 8 20 8"/>
                  </svg>
                </div>
                <div class="stat-info">
                  <span class="stat-number">{{ examStats.totalPapers }}</span>
                  <span class="stat-desc">试卷总数</span>
                </div>
              </div>
            </el-col>
            <el-col :span="6">
              <div class="stat-card">
                <div class="stat-icon-wrapper green">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                    <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/>
                    <circle cx="9" cy="7" r="4"/>
                    <path d="M23 21v-2a4 4 0 0 0-3-3.87"/>
                    <path d="M16 3.13a4 4 0 0 1 0 7.75"/>
                  </svg>
                </div>
                <div class="stat-info">
                  <span class="stat-number">{{ examStats.totalExams }}</span>
                  <span class="stat-desc">考试人次</span>
                </div>
              </div>
            </el-col>
            <el-col :span="6">
              <div class="stat-card">
                <div class="stat-icon-wrapper orange">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                    <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/>
                    <polyline points="22 4 12 14.01 9 11.01"/>
                  </svg>
                </div>
                <div class="stat-info">
                  <span class="stat-number">{{ examStats.avgScore }}</span>
                  <span class="stat-desc">平均分数</span>
                </div>
              </div>
            </el-col>
            <el-col :span="6">
              <div class="stat-card">
                <div class="stat-icon-wrapper purple">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                    <path d="M12 20V10"/>
                    <path d="M18 20V4"/>
                    <path d="M6 20v-4"/>
                  </svg>
                </div>
                <div class="stat-info">
                  <span class="stat-number">{{ examStats.passRate }}%</span>
                  <span class="stat-desc">及格率</span>
                </div>
              </div>
            </el-col>
          </el-row>

          <!-- 考试统计表格 -->
          <div v-if="paperStats.length > 0" class="stats-table">
            <h4>各试卷统计</h4>
            <el-table :data="paperStats" stripe>
              <el-table-column prop="paperTitle" label="试卷名称" min-width="180" />
              <el-table-column prop="totalCount" label="下发人数" width="100" />
              <el-table-column prop="completedCount" label="完成人数" width="100" />
              <el-table-column prop="completionRate" label="完成率" width="100">
                <template #default="{ row }">
                  {{ row.completionRate }}%
                </template>
              </el-table-column>
              <el-table-column prop="avgScore" label="平均分" width="80" />
              <el-table-column prop="maxScore" label="最高分" width="80" />
              <el-table-column prop="passRate" label="及格率" width="100">
                <template #default="{ row }">
                  {{ row.passRate }}%
                </template>
              </el-table-column>
              <el-table-column label="操作" width="100" fixed="right">
                <template #default="{ row }">
                  <el-button type="primary" link size="small" @click="viewPaperStats(row)">详情</el-button>
                </template>
              </el-table-column>
            </el-table>
          </div>
        </div>
      </el-tab-pane>
    </el-tabs>

    <!-- 智能组卷弹窗 -->
    <el-dialog v-model="showAutoGenerateDialog" title="智能组卷" width="700px" class="glass-dialog" :close-on-click-modal="false">
      <el-form :model="generateForm" label-width="100px" class="generate-form">
        <el-form-item label="试卷标题" required>
          <el-input v-model="generateForm.title" placeholder="请输入试卷标题" />
        </el-form-item>
        <el-form-item label="试卷说明">
          <el-input v-model="generateForm.description" type="textarea" :rows="2" placeholder="请输入试卷说明" />
        </el-form-item>
        <el-form-item label="及格分数">
          <el-input-number v-model="generateForm.passScore" :min="1" :max="100" />
        </el-form-item>
        <el-form-item label="时限(分钟)">
          <el-input-number v-model="generateForm.timeLimit" :min="5" :max="180" :step="5" />
        </el-form-item>
        
        <el-divider content-position="left">题型配置</el-divider>
        
        <div v-for="(qType, index) in generateForm.questionTypes" :key="index" class="question-type-item">
          <el-form-item :label="getTypeName(qType.type)" label-width="80px">
            <el-input-number v-model="qType.count" :min="0" :max="50" placeholder="数量" style="width: 100px" />
            <span class="type-label">题 ×</span>
            <el-input-number v-model="qType.score" :min="1" :max="100" placeholder="分值" style="width: 100px" />
            <span class="type-label">分</span>
          </el-form-item>
        </div>

        <el-form-item label="难度配置">
          <div class="difficulty-config">
            <span>简单</span>
            <el-slider v-model="generateForm.difficulty.easy" :min="0" :max="100" :step="5" show-input input-size="small" style="width: 200px" />
            <span>中等</span>
            <el-slider v-model="generateForm.difficulty.medium" :min="0" :max="100" :step="5" show-input input-size="small" style="width: 200px" />
            <span>困难</span>
            <el-slider v-model="generateForm.difficulty.hard" :min="0" :max="100" :step="5" show-input input-size="small" style="width: 200px" />
          </div>
        </el-form-item>

        <el-form-item label="分类配置">
          <div class="category-config">
            <div v-for="(cat, index) in generateForm.categories" :key="index" class="category-item">
              <el-select v-model="cat.categoryId" placeholder="选择分类" style="width: 180px">
                <el-option v-for="c in categories" :key="c.id" :label="c.name" :value="c.id" />
              </el-select>
              <span class="type-label">权重</span>
              <el-input-number v-model="cat.weight" :min="1" :max="100" :step="5" style="width: 100px" />
              <span class="type-label">%</span>
              <el-button type="danger" link @click="removeCategory(index)">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="16" height="16">
                  <path d="M18 6 6 18M6 6l12 12"/>
                </svg>
              </el-button>
            </div>
            <el-button type="primary" link @click="addCategory">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="14" height="14">
                <path d="M12 5v14M5 12h14"/>
              </svg>
              添加分类
            </el-button>
          </div>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="showAutoGenerateDialog = false">取消</el-button>
        <el-button type="primary" :loading="generating" @click="handleAutoGenerate">
          开始组卷
        </el-button>
      </template>
    </el-dialog>

    <!-- 题目管理弹窗 -->
    <el-dialog v-model="showQuestionDialog" title="题目管理" width="900px" class="glass-dialog">
      <div class="question-toolbar">
        <el-button type="primary" @click="showAddQuestionDialog = true">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="14" height="14">
            <path d="M12 5v14M5 12h14"/>
          </svg>
          添加题目
        </el-button>
        <el-form :inline="true">
          <el-form-item label="题型">
            <el-select v-model="questionQuery.type" placeholder="全部" clearable style="width: 120px">
              <el-option label="单选题" value="single_choice" />
              <el-option label="多选题" value="multiple_choice" />
              <el-option label="判断题" value="judge" />
              <el-option label="简答题" value="essay" />
            </el-select>
          </el-form-item>
          <el-form-item label="难度">
            <el-select v-model="questionQuery.difficulty" placeholder="全部" clearable style="width: 100px">
              <el-option label="简单" value="easy" />
              <el-option label="中等" value="medium" />
              <el-option label="困难" value="hard" />
            </el-select>
          </el-form-item>
          <el-form-item>
            <el-button type="primary" @click="loadQuestions">搜索</el-button>
          </el-form-item>
        </el-form>
      </div>

      <el-table :data="questions" v-loading="questionLoading" stripe>
        <el-table-column prop="type" label="题型" width="100">
          <template #default="{ row }">
            {{ getTypeName(row.type) }}
          </template>
        </el-table-column>
        <el-table-column prop="difficulty" label="难度" width="80">
          <template #default="{ row }">
            <el-tag :type="getDifficultyType(row.difficulty)" size="small">
              {{ getDifficultyText(row.difficulty) }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="content" label="题目内容" min-width="300" show-overflow-tooltip />
        <el-table-column prop="score" label="分值" width="60" />
        <el-table-column prop="usageCount" label="使用次数" width="80" />
        <el-table-column label="操作" width="150" fixed="right">
          <template #default="{ row }">
            <el-button type="primary" link size="small" @click="editQuestion(row)">编辑</el-button>
            <el-button type="danger" link size="small" @click="deleteQuestion(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>
      <el-pagination
        v-model:current-page="questionQuery.page"
        v-model:page-size="questionQuery.pageSize"
        :total="questionTotal"
        :page-sizes="[10, 20, 50]"
        layout="total, sizes, prev, pager, next"
        class="pagination"
        @size-change="loadQuestions"
        @current-change="loadQuestions"
      />
    </el-dialog>

    <!-- 添加/编辑题目弹窗 -->
    <el-dialog v-model="showAddQuestionDialog" :title="editingQuestion.id ? '编辑题目' : '添加题目'" width="600px" class="glass-dialog">
      <el-form :model="editingQuestion" label-width="90px">
        <el-form-item label="题型" required>
          <el-select v-model="editingQuestion.type" :disabled="!!editingQuestion.id" style="width: 100%">
            <el-option label="单选题" value="single_choice" />
            <el-option label="多选题" value="multiple_choice" />
            <el-option label="判断题" value="judge" />
            <el-option label="简答题" value="essay" />
          </el-select>
        </el-form-item>
        <el-form-item label="难度" required>
          <el-select v-model="editingQuestion.difficulty" style="width: 100%">
            <el-option label="简单" value="easy" />
            <el-option label="中等" value="medium" />
            <el-option label="困难" value="hard" />
          </el-select>
        </el-form-item>
        <el-form-item label="题目内容" required>
          <el-input v-model="editingQuestion.content" type="textarea" :rows="3" placeholder="请输入题目内容" />
        </el-form-item>
        
        <el-form-item v-if="editingQuestion.type !== 'judge' && editingQuestion.type !== 'essay'" label="选项">
          <div class="options-editor">
            <div v-for="(opt, index) in editingQuestion.options" :key="index" class="option-item">
              <span class="option-key">{{ String.fromCharCode(65 + index) }}</span>
              <el-input v-model="opt.value" placeholder="选项内容" style="flex: 1" />
              <el-button type="danger" link @click="removeOption(index)">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="14" height="14">
                  <path d="M18 6 6 18M6 6l12 12"/>
                </svg>
              </el-button>
            </div>
            <el-button type="primary" link @click="addOption" :disabled="editingQuestion.options.length >= 6">
              添加选项
            </el-button>
          </div>
        </el-form-item>

        <el-form-item label="正确答案" required>
          <template v-if="editingQuestion.type === 'judge'">
            <el-radio-group v-model="editingQuestion.correctAnswer">
              <el-radio label="A">正确</el-radio>
              <el-radio label="B">错误</el-radio>
            </el-radio-group>
          </template>
          <template v-else-if="editingQuestion.type === 'essay'">
            <el-input v-model="editingQuestion.correctAnswer" type="textarea" :rows="2" placeholder="请输入参考答案" />
          </template>
          <template v-else-if="editingQuestion.type === 'multiple_choice'">
            <el-checkbox-group v-model="editingQuestion.correctAnswer">
              <el-checkbox v-for="(opt, index) in editingQuestion.options" :key="index" :label="String.fromCharCode(65 + index)">
                {{ String.fromCharCode(65 + index) }}
              </el-checkbox>
            </el-checkbox-group>
          </template>
          <template v-else>
            <el-radio-group v-model="editingQuestion.correctAnswer">
              <el-radio v-for="(opt, index) in editingQuestion.options" :key="index" :label="String.fromCharCode(65 + index)">
                {{ String.fromCharCode(65 + index) }}
              </el-radio>
            </el-radio-group>
          </template>
        </el-form-item>

        <el-form-item label="分值">
          <el-input-number v-model="editingQuestion.score" :min="1" :max="100" />
        </el-form-item>
        <el-form-item label="答案解析">
          <el-input v-model="editingQuestion.analysis" type="textarea" :rows="2" placeholder="请输入答案解析" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="showAddQuestionDialog = false">取消</el-button>
        <el-button type="primary" @click="saveQuestion">保存</el-button>
      </template>
    </el-dialog>

    <!-- 试卷预览弹窗 -->
    <el-dialog v-model="showPreviewDialog" title="试卷预览" width="800px" class="glass-dialog preview-dialog">
      <div v-if="previewPaper" class="preview-paper">
        <div class="preview-header">
          <h2>{{ previewPaper.title }}</h2>
          <div class="preview-info">
            <span>总分：{{ previewPaper.totalScore }}</span>
            <span>及格：{{ previewPaper.passScore }}</span>
            <span>时限：{{ previewPaper.timeLimit }}分钟</span>
            <span>题目：{{ previewPaper.questionCount }}题</span>
          </div>
        </div>
        <div class="preview-description" v-if="previewPaper.description">
          {{ previewPaper.description }}
        </div>
        <div class="preview-questions">
          <div v-for="(q, index) in previewPaper.questions" :key="q.id" class="preview-question">
            <div class="question-header">
              <span class="question-number">{{ index + 1 }}.</span>
              <span class="question-type-tag">{{ getTypeName(q.type) }}</span>
              <span class="question-score">({{ q.score }}分)</span>
            </div>
            <div class="question-content">{{ q.content }}</div>
            <div v-if="q.options && (q.type === 'single_choice' || q.type === 'multiple_choice')" class="question-options">
              <div v-for="(opt, optIndex) in JSON.parse(q.options)" :key="optIndex" class="question-option">
                {{ opt.key }}. {{ opt.value }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </el-dialog>

    <!-- 下发考试弹窗 -->
    <el-dialog v-model="showDispatchDialog" title="下发考试" width="500px" class="glass-dialog">
      <el-form :model="dispatchForm" label-width="100px">
        <el-form-item label="选择试卷">
          <span class="dispatch-paper-title">{{ currentPaper?.title }}</span>
        </el-form-item>
        <el-form-item label="下发方式" required>
          <el-radio-group v-model="dispatchForm.dispatchType">
            <el-radio label="organization">按组织下发</el-radio>
            <el-radio label="user">按用户下发</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item v-if="dispatchForm.dispatchType === 'organization'" label="选择组织">
          <el-tree-select
            v-model="dispatchForm.organizationIds"
            :data="organizationTree"
            :props="{ label: 'name', children: 'children', value: 'id' }"
            multiple
            check-strictly
            placeholder="请选择组织"
            style="width: 100%"
          />
        </el-form-item>
        <el-form-item v-if="dispatchForm.dispatchType === 'user'" label="选择用户">
          <el-select v-model="dispatchForm.userIds" multiple filterable placeholder="请选择用户" style="width: 100%">
            <el-option v-for="u in users" :key="u.id" :label="u.nickname || u.username" :value="u.id" />
          </el-select>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="showDispatchDialog = false">取消</el-button>
        <el-button type="primary" :loading="dispatching" @click="handleDispatch">确认下发</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import request from '@/utils/request'

const activeTab = ref('papers')
const paperLoading = ref(false)
const recordLoading = ref(false)
const questionLoading = ref(false)
const generating = ref(false)
const dispatching = ref(false)

const papers = ref([])
const records = ref([])
const questions = ref([])
const categories = ref([])
const users = ref([])
const organizationTree = ref([])
const paperStats = ref([])

const paperTotal = ref(0)
const recordTotal = ref(0)
const questionTotal = ref(0)

const paperQuery = reactive({
  page: 1,
  pageSize: 8,
  keyword: '',
  status: '',
  sourceType: ''
})

const recordQuery = reactive({
  page: 1,
  pageSize: 10,
  paperId: '',
  status: ''
})

const questionQuery = reactive({
  page: 1,
  pageSize: 10,
  type: '',
  difficulty: ''
})

const examStats = reactive({
  totalPapers: 0,
  totalExams: 0,
  avgScore: 0,
  passRate: 0
})

// 弹窗控制
const showAutoGenerateDialog = ref(false)
const showQuestionDialog = ref(false)
const showAddQuestionDialog = ref(false)
const showPreviewDialog = ref(false)
const showDispatchDialog = ref(false)

const previewPaper = ref(null)
const currentPaper = ref(null)

const generateForm = reactive({
  title: '',
  description: '',
  passScore: 60,
  timeLimit: 60,
  questionTypes: [
    { type: 'single_choice', count: 10, score: 5 },
    { type: 'multiple_choice', count: 5, score: 10 },
    { type: 'judge', count: 10, score: 3 }
  ],
  difficulty: { easy: 30, medium: 50, hard: 20 },
  categories: []
})

const editingQuestion = reactive({
  id: '',
  type: 'single_choice',
  difficulty: 'medium',
  content: '',
  options: [
    { key: 'A', value: '' },
    { key: 'B', value: '' },
    { key: 'C', value: '' },
    { key: 'D', value: '' }
  ],
  correctAnswer: '',
  score: 10,
  analysis: ''
})

const dispatchForm = reactive({
  dispatchType: 'organization',
  organizationIds: [],
  userIds: []
})

// 加载试卷列表
const loadPapers = async () => {
  paperLoading.value = true
  try {
    const res = await request.get('/api/exam/papers', { params: paperQuery })
    papers.value = res.data || []
    paperTotal.value = res.data?.total || papers.value.length
  } catch (e) {
    ElMessage.error('加载试卷失败')
  } finally {
    paperLoading.value = false
  }
}

// 加载考试记录
const loadRecords = async () => {
  recordLoading.value = true
  try {
    const res = await request.get('/api/exam/records', { params: recordQuery })
    records.value = res.data || []
    recordTotal.value = res.data?.total || records.value.length
  } catch (e) {
    ElMessage.error('加载记录失败')
  } finally {
    recordLoading.value = false
  }
}

// 加载题目列表
const loadQuestions = async () => {
  questionLoading.value = true
  try {
    const res = await request.get('/api/exam/questions', { params: questionQuery })
    questions.value = res.data || []
    questionTotal.value = res.data?.total || questions.value.length
  } catch (e) {
    ElMessage.error('加载题目失败')
  } finally {
    questionLoading.value = false
  }
}

// 加载分类
const loadCategories = async () => {
  try {
    const res = await request.get('/api/exam/categories')
    categories.value = res.data || []
  } catch (e) {
    categories.value = []
  }
}

// 加载用户
const loadUsers = async () => {
  try {
    const res = await request.get('/users', { params: { page: 1, pageSize: 100 } })
    users.value = res.data || []
  } catch (e) {
    users.value = []
  }
}

// 加载组织树
const loadOrganizations = async () => {
  try {
    const res = await request.get('/organizations/tree')
    organizationTree.value = res.data || []
  } catch (e) {
    organizationTree.value = []
  }
}

// 加载统计
const loadExamStats = async () => {
  try {
    const res = await request.get('/api/exam/statistics/summary')
    Object.assign(examStats, res.data || {})
  } catch (e) {
    // ignore
  }
}

// 加载试卷统计
const loadPaperStats = async () => {
  try {
    const res = await request.get('/api/exam/statistics/papers')
    paperStats.value = res.data || []
  } catch (e) {
    paperStats.value = []
  }
}

// 重置查询
const resetPaperQuery = () => {
  paperQuery.keyword = ''
  paperQuery.status = ''
  paperQuery.sourceType = ''
  loadPapers()
}

const resetRecordQuery = () => {
  recordQuery.paperId = ''
  recordQuery.status = ''
  loadRecords()
}

// 智能组卷
const handleAutoGenerate = async () => {
  if (!generateForm.title) {
    ElMessage.warning('请输入试卷标题')
    return
  }
  generating.value = true
  try {
    await request.post('/api/exam/papers/auto-generate', generateForm)
    ElMessage.success('组卷成功')
    showAutoGenerateDialog.value = false
    loadPapers()
    // 重置表单
    generateForm.title = ''
    generateForm.description = ''
  } catch (e) {
    ElMessage.error('组卷失败')
  } finally {
    generating.value = false
  }
}

// 试卷操作
const handlePreview = async (paper) => {
  try {
    const res = await request.get(`/api/exam/papers/${paper.id}`, { params: { includeAnswer: false } })
    previewPaper.value = res.data
    showPreviewDialog.value = true
  } catch (e) {
    ElMessage.error('加载预览失败')
  }
}

const handleCommand = async (cmd, paper) => {
  currentPaper.value = paper
  switch (cmd) {
    case 'publish':
      await handlePublish(paper)
      break
    case 'dispatch':
      showDispatchDialog.value = true
      break
    case 'statistics':
      await viewPaperStats({ paperId: paper.id, paperTitle: paper.title })
      activeTab.value = 'statistics'
      break
    case 'delete':
      await handleDelete(paper)
      break
  }
}

const handlePublish = async (paper) => {
  try {
    await request.post(`/api/exam/papers/${paper.id}/publish`)
    ElMessage.success('发布成功')
    loadPapers()
  } catch (e) {
    ElMessage.error('发布失败')
  }
}

const handleDelete = async (paper) => {
  try {
    await ElMessageBox.confirm('确定要删除该试卷吗？', '提示', { type: 'warning' })
    await request.delete(`/api/exam/papers/${paper.id}`)
    ElMessage.success('删除成功')
    loadPapers()
  } catch (e) {
    if (e !== 'cancel') ElMessage.error('删除失败')
  }
}

// 下发考试
const handleDispatch = async () => {
  if (dispatchForm.dispatchType === 'organization' && dispatchForm.organizationIds.length === 0) {
    return ElMessage.warning('请选择组织')
  }
  if (dispatchForm.dispatchType === 'user' && dispatchForm.userIds.length === 0) {
    return ElMessage.warning('请选择用户')
  }
  dispatching.value = true
  try {
    await request.post('/api/exam/dispatch', {
      paperId: currentPaper.value.id,
      ...dispatchForm
    })
    ElMessage.success('下发成功')
    showDispatchDialog.value = false
  } catch (e) {
    ElMessage.error('下发失败')
  } finally {
    dispatching.value = false
  }
}

// 查看答题详情
const viewAnswerDetails = async (record) => {
  try {
    const res = await request.get(`/api/exam/records/${record.id}/answers`)
    ElMessage.info(`共 ${res.data?.length || 0} 道题目，已答题`)
  } catch (e) {
    ElMessage.error('加载详情失败')
  }
}

// 查看试卷统计
const viewPaperStats = async (paper) => {
  try {
    const res = await request.get(`/api/exam/statistics/${paper.paperId}`)
    ElMessageBox.alert(`
      <div style="text-align:left">
        <p>试卷：${res.data?.paperTitle}</p>
        <p>下发人数：${res.data?.totalCount || 0}</p>
        <p>完成人数：${res.data?.completedCount || 0}</p>
        <p>完成率：${res.data?.completionRate || 0}%</p>
        <p>平均分：${res.data?.avgScore || 0}</p>
        <p>及格率：${res.data?.passRate || 0}%</p>
      </div>
    `, '考试统计', { dangerouslyUseHTMLString: true })
  } catch (e) {
    ElMessage.error('加载统计失败')
  }
}

// 题目管理
const editQuestion = (question) => {
  Object.assign(editingQuestion, {
    id: question.id,
    type: question.type,
    difficulty: question.difficulty,
    content: question.content,
    options: question.options ? JSON.parse(question.options) : [
      { key: 'A', value: '' },
      { key: 'B', value: '' }
    ],
    correctAnswer: question.answer ? JSON.parse(question.answer)[0] : '',
    score: question.score,
    analysis: question.analysis || ''
  })
  showAddQuestionDialog.value = true
}

const saveQuestion = async () => {
  if (!editingQuestion.content) {
    return ElMessage.warning('请输入题目内容')
  }
  try {
    const data = { ...editingQuestion }
    data.options = editingQuestion.options
    data.answer = JSON.stringify([editingQuestion.correctAnswer])
    if (editingQuestion.id) {
      await request.put(`/api/exam/questions/${editingQuestion.id}`, data)
      ElMessage.success('更新成功')
    } else {
      await request.post('/api/exam/questions', data)
      ElMessage.success('添加成功')
    }
    showAddQuestionDialog.value = false
    loadQuestions()
  } catch (e) {
    ElMessage.error('保存失败')
  }
}

const deleteQuestion = async (question) => {
  try {
    await ElMessageBox.confirm('确定要删除该题目吗？', '提示', { type: 'warning' })
    await request.delete(`/api/exam/questions/${question.id}`)
    ElMessage.success('删除成功')
    loadQuestions()
  } catch (e) {
    if (e !== 'cancel') ElMessage.error('删除失败')
  }
}

const addOption = () => {
  const key = String.fromCharCode(65 + editingQuestion.options.length)
  editingQuestion.options.push({ key, value: '' })
}

const removeOption = (index) => {
  editingQuestion.options.splice(index, 1)
  editingQuestion.options.forEach((opt, i) => {
    opt.key = String.fromCharCode(65 + i)
  })
}

// 分类配置
const addCategory = () => {
  generateForm.categories.push({ categoryId: '', weight: 10 })
}

const removeCategory = (index) => {
  generateForm.categories.splice(index, 1)
}

// 工具函数
const getStatusType = (status) => {
  const map = { draft: 'info', published: 'success', archived: 'warning' }
  return map[status] || 'info'
}

const getStatusText = (status) => {
  const map = { draft: '草稿', published: '已发布', archived: '已归档' }
  return map[status] || status
}

const getSourceTypeText = (type) => {
  const map = { manual: '手动组卷', auto: '智能组卷', template: '模板组卷' }
  return map[type] || type
}

const getRecordStatusType = (status) => {
  const map = { not_started: 'info', in_progress: 'warning', submitted: '', graded: 'success' }
  return map[status] || 'info'
}

const getRecordStatusText = (status) => {
  const map = { not_started: '未开始', in_progress: '进行中', submitted: '已提交', graded: '已评分' }
  return map[status] || status
}

const getTypeName = (type) => {
  const map = {
    single_choice: '单选题',
    multiple_choice: '多选题',
    judge: '判断题',
    essay: '简答题'
  }
  return map[type] || type
}

const getDifficultyType = (diff) => {
  const map = { easy: 'success', medium: 'warning', hard: 'danger' }
  return map[diff] || 'info'
}

const getDifficultyText = (diff) => {
  const map = { easy: '简单', medium: '中等', hard: '困难' }
  return map[diff] || diff
}

const formatDate = (date) => {
  if (!date) return '-'
  return new Date(date).toLocaleString('zh-CN')
}

const formatDuration = (seconds) => {
  if (!seconds) return '-'
  const mins = Math.floor(seconds / 60)
  const secs = seconds % 60
  return `${mins}分${secs}秒`
}

const handleTabChange = (tab) => {
  if (tab === 'statistics') {
    loadExamStats()
    loadPaperStats()
  }
}

onMounted(() => {
  loadPapers()
  loadCategories()
  loadUsers()
  loadOrganizations()
})
</script>

<style lang="scss" scoped>
.exam-container {
  padding: 24px;
  min-height: 100vh;
  background: #ffffff;
  position: relative;
  overflow: hidden;
}

.bg-decoration {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  pointer-events: none;
  z-index: 0;
}

.bg-circle {
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(135deg, rgba(82,183,136,0.08), rgba(149,213,178,0.04));
}

.bg-circle-1 { width: 400px; height: 400px; top: -100px; right: -100px; }
.bg-circle-2 { width: 300px; height: 300px; bottom: 5%; left: -80px; }

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 24px;
  position: relative;
  z-index: 1;
}

.header-title {
  display: flex;
  align-items: center;
  gap: 16px;

  .header-icon { width: 40px; height: 40px; color: #52b788; }
  h1 { margin: 0; font-size: 26px; font-weight: 700; color: #333333; }
}

.header-actions { display: flex; gap: 12px; }

.btn-primary {
  background: linear-gradient(135deg, #52b788, #2d6a4f) !important;
  border: none !important;
  display: flex !important;
  align-items: center !important;
  gap: 8px;

  svg { width: 18px; height: 18px; }
  &:hover { transform: translateY(-2px); box-shadow: 0 8px 20px rgba(82,183,136,0.3); }
}

.btn-secondary {
  background: rgba(255,255,255,0.8) !important;
  border: 1px solid rgba(82,183,136,0.3) !important;
  color: #2d6a4f !important;
  display: flex !important;
  align-items: center !important;
  gap: 8px;

  svg { width: 18px; height: 18px; }
}

.glass-card {
  background: rgba(255,255,255,0.85);
  backdrop-filter: blur(20px);
  border: 1px solid rgba(255,255,255,0.5);
  border-radius: 16px;
  padding: 24px;
  position: relative;
}

.glass-tabs {
  position: relative;
  z-index: 1;
  
  :deep(.el-tabs__header) { margin-bottom: 20px; }
  :deep(.el-tabs__item.is-active) { color: #52b788; }
  :deep(.el-tabs__active-bar) { background-color: #52b788; }
  :deep(.el-tabs__nav-wrap::after) { background-color: rgba(82,183,136,0.2); }
}

.filter-card { margin-bottom: 20px; }

.paper-list-card { min-height: 400px; }

.paper-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(340px, 1fr));
  gap: 20px;
}

.paper-card {
  background: rgba(82,183,136,0.04);
  border: 1px solid rgba(82,183,136,0.12);
  border-radius: 16px;
  padding: 20px;
  transition: all 0.3s ease;

  &:hover {
    transform: translateY(-4px);
    box-shadow: 0 8px 24px rgba(82,183,136,0.15);
  }
}

.paper-card-header {
  margin-bottom: 16px;
  .paper-title-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 8px;
  }
  .paper-title {
    font-size: 16px;
    font-weight: 600;
    color: #333333;
  }
}

.paper-card-body {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 12px;
  padding: 16px 0;
  border-top: 1px solid rgba(82,183,136,0.1);
  border-bottom: 1px solid rgba(82,183,136,0.1);
}

.stat-item {
  text-align: center;
  .stat-label { display: block; font-size: 12px; color: #666666; margin-bottom: 4px; }
  .stat-value { display: block; font-size: 16px; font-weight: 600; color: #333333; }
}

.paper-card-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 16px;
}

.paper-date { font-size: 12px; color: #9ca3af; }
.paper-actions { display: flex; gap: 12px; }

.empty-state {
  text-align: center;
  padding: 60px 20px;
  color: #666666;
  svg { color: #d1d5db; margin-bottom: 16px; }
  p { margin-bottom: 20px; }
}

.pagination { margin-top: 20px; justify-content: flex-end; }

// 统计卡片
.stats-row { margin-bottom: 24px; }

.stat-card {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 24px;
  background: rgba(255,255,255,0.9);
  border-radius: 16px;
  box-shadow: 0 2px 12px rgba(0,0,0,0.05);
}

.stat-icon-wrapper {
  width: 56px;
  height: 56px;
  border-radius: 14px;
  display: flex;
  align-items: center;
  justify-content: center;
  
  svg { width: 28px; height: 28px; }
  
  &.blue { background: rgba(59,130,246,0.1); svg { color: #3b82f6; } }
  &.green { background: rgba(82,183,136,0.1); svg { color: #52b788; } }
  &.orange { background: rgba(249,115,22,0.1); svg { color: #f97316; } }
  &.purple { background: rgba(168,85,247,0.1); svg { color: #a855f7; } }
}

.stat-info {
  .stat-number { display: block; font-size: 28px; font-weight: 700; color: #333333; }
  .stat-desc { display: block; font-size: 14px; color: #666666; }
}

.stats-table {
  margin-top: 24px;
  h4 { margin-bottom: 16px; color: #333333; }
}

// 弹窗样式
.glass-dialog {
  :deep(.el-dialog) {
    background: rgba(255,255,255,0.95);
    backdrop-filter: blur(24px);
    border-radius: 20px;
  }
}

.generate-form {
  .type-label { margin: 0 8px; color: #666666; }
}

.difficulty-config {
  display: flex;
  flex-direction: column;
  gap: 8px;
  align-items: flex-start;
  span { font-size: 13px; color: #666666; width: 40px; }
}

.category-config {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.category-item {
  display: flex;
  align-items: center;
  gap: 8px;
}

.options-editor {
  width: 100%;
  .option-item {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 8px;
  }
  .option-key {
    width: 24px;
    height: 24px;
    background: rgba(82,183,136,0.1);
    border-radius: 6px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 12px;
    font-weight: 600;
    color: #2d6a4f;
  }
}

.preview-dialog {
  :deep(.el-dialog__body) { max-height: 70vh; overflow-y: auto; }
}

.preview-paper {
  .preview-header {
    text-align: center;
    padding-bottom: 20px;
    border-bottom: 2px solid rgba(82,183,136,0.2);
    margin-bottom: 20px;
    h2 { margin: 0 0 12px; color: #333333; }
  }
  .preview-info {
    display: flex;
    justify-content: center;
    gap: 24px;
    font-size: 14px;
    color: #666666;
  }
  .preview-description {
    padding: 16px;
    background: rgba(82,183,136,0.05);
    border-radius: 12px;
    margin-bottom: 20px;
    color: #4b5563;
  }
}

.preview-question {
  padding: 16px;
  background: rgba(82,183,136,0.03);
  border-radius: 12px;
  margin-bottom: 16px;
  
  .question-header {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 12px;
  }
  .question-type-tag {
    font-size: 12px;
    padding: 2px 8px;
    background: rgba(82,183,136,0.15);
    color: #2d6a4f;
    border-radius: 4px;
  }
  .question-score { font-size: 12px; color: #666666; }
  .question-content { font-size: 14px; color: #333333; margin-bottom: 12px; }
  .question-options { padding-left: 20px; }
  .question-option {
    padding: 6px 0;
    font-size: 13px;
    color: #4b5563;
  }
}

.dispatch-paper-title {
  font-weight: 600;
  color: #333333;
}

.question-toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
}

:deep(.el-input-number) {
  .el-input__wrapper { border-radius: 8px; }
}

:deep(.el-select__wrapper) { border-radius: 8px; }
</style>
